### ISSUE TITLE
Separate the UI to a different repository

### ISSUE THREAD

**Issue by JaniAnttonen** [eqlabs/starknet-multisig#56]
This repository can still be named `starknet-multisig`.

TODO (in order!):

- [x] Separate the UI to a repo called ´starknet-multisig-ui`
- [x] Close all pending pull requests from this contract repo
- [ ] Remove the frontend code from this repo in another PR

**Comment by JaniAnttonen** [comment]
1. https://github.com/eqlabs/starknet-multisig-ui

**Comment by JaniAnttonen** [comment]
> Remove the frontend code from this repo in another PR

Wanna do this, @microbecode? :)

**Comment by microbecode** [comment]
You mean just delete the code from here? I think it's better you do it, you know better what scripts to also remove and so on

**Comment by JaniAnttonen** [comment]
Ok, I'll do it soonish 👍
